#!/usr/bin/env python
import sys

import rospy

import kuri_edu

if __name__ == '__main__':

    # If the script was run with 'coverage' we're going to run the python
    # coverage module to generate line coverage
    if "coverage" in sys.argv:
        import coverage
        cov = coverage.Coverage(auto_data=True)
        cov.start()
        # reload(kuri_edu.safety_controller)

    rospy.init_node('safety_controller')

    # safety_controller = kuri_edu.SafetyController()

    try:
        # safety_controller.run()
    finally:
        # safety_controller.shutdown()
        if 'cov' in locals():
            cov.stop()
