#!/usr/bin/env python
import sys

import rospy

import kuri_edu

if __name__ == '__main__':

    # If the script was run with 'coverage' we're going to run the python
    # coverage module to generate line coverage
    if "coverage" in sys.argv:
        import coverage
        cov = coverage.Coverage(auto_data=True)
        cov.start()
        reload(kuri_edu.chest_light_controller)

    rospy.init_node('chest_light_controller')

    chest_led_controller = kuri_edu.ChestLedController()

    try:
        chest_led_controller.run()
    finally:
        chest_led_controller.shutdown()
        if 'cov' in locals():
            cov.stop()
