#!/usr/bin/env python
import sys

import rospy

import kuri_edu

if __name__ == '__main__':

    # If the script was run with 'coverage' we're going to run the python
    # coverage module to generate line coverage
    if "coverage" in sys.argv:
        import coverage
        cov = coverage.Coverage(auto_data=True)
        cov.start()
        reload(kuri_edu.joystick_teleop)

    rospy.init_node('joystick_teleop')
    joystick_teleop = kuri_edu.Joystick()

    try:
        joystick_teleop.run()
    finally:
        joystick_teleop.shutdown()
        if 'cov' in locals():
            cov.stop()
