#!/usr/bin/env python
import sys

import rospy

import kuri_edu

if __name__ == '__main__':

    # If the script was run with 'coverage' we're going to run the python
    # coverage module to generate line coverage
    if "coverage" in sys.argv:
        import coverage
        cov = coverage.Coverage(auto_data=True)
        cov.start()
        reload(kuri_edu.nav_controller)

    rospy.init_node('nav_controller')

    nav_controller = kuri_edu.NavController()

    try:
        nav_controller.run()
    finally:
        nav_controller.shutdown()
        if 'cov' in locals():
            cov.stop()
