#!/usr/bin/env python
import rospy

import kuri_edu

if __name__ == '__main__':

    rospy.init_node('safety_controller')

    safety_controller = kuri_edu.SafetyController()

    try:
        safety_controller.run()
    finally:
        safety_controller.shutdown()
