#!/usr/bin/env python
import rospy

import kuri_edu

if __name__ == '__main__':

    rospy.init_node('keyboard_teleop_adapter')

    # The simple kuri client will disable all safety events so that the
    # robot can be driven by a keyboard teleop node.
    # See http://wiki.ros.org/teleop_twist_keyboard for how to run a keyboard
    # teleop node
    client = kuri_edu.SimpleKuriClient()
    batt_mon = kuri_edu.BatteryMonitor()

    try:
        rospy.spin()
    finally:
        client.shutdown()
        batt_mon.shutdown()
